// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXSmukUDjhuzOHjAvhpIEJdfOYPWB4Rcc',
    appId: '1:1061240850310:web:d63c4e8166279361d14e07',
    messagingSenderId: '1061240850310',
    projectId: 'mnymngm',
    authDomain: 'mnymngm.firebaseapp.com',
    storageBucket: 'mnymngm.firebasestorage.app',
    measurementId: 'G-P3H8CGQTCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLWo1zyJUBIg_MeSPjIHr8UErFBe10JPI',
    appId: '1:1061240850310:android:f6f776eb05fa21c7d14e07',
    messagingSenderId: '1061240850310',
    projectId: 'mnymngm',
    storageBucket: 'mnymngm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQIc7yX1VEs4hPDlAlr8MLWwwxyFfZBZY',
    appId: '1:1061240850310:ios:de3f05210162cde5d14e07',
    messagingSenderId: '1061240850310',
    projectId: 'mnymngm',
    storageBucket: 'mnymngm.firebasestorage.app',
    iosBundleId: 'com.example.mnyMngm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQIc7yX1VEs4hPDlAlr8MLWwwxyFfZBZY',
    appId: '1:1061240850310:ios:de3f05210162cde5d14e07',
    messagingSenderId: '1061240850310',
    projectId: 'mnymngm',
    storageBucket: 'mnymngm.firebasestorage.app',
    iosBundleId: 'com.example.mnyMngm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXSmukUDjhuzOHjAvhpIEJdfOYPWB4Rcc',
    appId: '1:1061240850310:web:15aa09f1a70b3048d14e07',
    messagingSenderId: '1061240850310',
    projectId: 'mnymngm',
    authDomain: 'mnymngm.firebaseapp.com',
    storageBucket: 'mnymngm.firebasestorage.app',
    measurementId: 'G-V1HL5J0XVD',
  );
}
